# test for breaking changes on the different bundle projects
#todo: use a matrix syntax?

name: "Test the bundles' dependencies"

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  symfony-test:
    name: "Test symfony bundle"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "copy the project"
        run: rsync -av . tests/dependencies/copy/ --exclude tests --exclude vendor

      - name: "Clone the bundle project"
        run: git clone https://github.com/thecodingmachine/graphqlite-bundle.git
        working-directory: "tests/dependencies"

      - name: "edit the composer.json"
        run: php ./makeComposerLocal.php graphqlite-bundle/composer.json
        working-directory: "tests/dependencies"

      - name: "install dependencies"
        run: composer install
        working-directory: "tests/dependencies/graphqlite-bundle"


  universal-service-provider-test:
    name: "Test graphqlite-universal-service-provider"
    runs-on: "ubuntu-latest"
    if: ${{ false }} # TODO: Revisit and make a decision
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "copy the project"
        run: rsync -av . tests/dependencies/copy/ --exclude tests --exclude vendor

      - name: "Clone the bundle project"
        run: git clone https://github.com/thecodingmachine/graphqlite-universal-service-provider.git
        working-directory: "tests/dependencies"

      - name: "edit the composer.json"
        run: php ./makeComposerLocal.php graphqlite-universal-service-provider/composer.json
        working-directory: "tests/dependencies"

      - name: "install dependencies"
        run: composer install
        working-directory: "tests/dependencies/graphqlite-universal-service-provider"


  laravel-test:
    name: "Test graphqlite-laravel"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "copy the project"
        run: rsync -av . tests/dependencies/copy/ --exclude tests --exclude vendor

      - name: "Clone the bundle project"
        run: git clone https://github.com/thecodingmachine/graphqlite-laravel.git
        working-directory: "tests/dependencies"

      - name: "edit the composer.json"
        run: php ./makeComposerLocal.php graphqlite-laravel/composer.json
        working-directory: "tests/dependencies"

      - name: "install dependencies"
        run: composer install
        working-directory: "tests/dependencies/graphqlite-laravel"
